### ISSUE TITLE
Smart search

### ISSUE THREAD

**Issue by halfempty** [everythingtype/etc-nyc#18]
**@gehalber says:**

> Are there any easy plug ins out there that would allow us to do a smart search, along these lines... where the search results are fed while typing in a key word http://icaphila.org/

**Comment by gehalber** [comment]
What if we wanted to add some key terms to the search section. I'm imagining this is kind of a black veil that comes down over content when you click on Search. You still have the same Search functionality, but you also have these keyterms in case you don't really know what to search for, which may very well be the case. What do you think?

![screen shot 2015-01-20 at 12 51 41 am](https://cloud.githubusercontent.com/assets/6076488/5812745/eee1ca5e-a03e-11e4-874c-d53a168a611d.png)
