### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by halfempty** [everythingtype/etc-nyc#22]

**Comment by gehalber** [comment]
Still need to work out the tweaks to mobile. Look for more on this in the coming weeks.

**Comment by halfempty** [comment]
@gehalber I've put in the "srcset" tags, which are for sending images of the correct resolution depending on the visitor's device.

**Comment by halfempty** [comment]
@gehalber I've come to realize there's a part of "srcset" I've been missing, which still needs to be addressed.

**Comment by halfempty** [comment]
@gehalber I've made some great progress on implementing responsive images within WordPress. I've applied the latest version of my code for this to both ETC and JSA.

**Comment by gehalber** [comment]
Great!
