### ISSUE TITLE
Homepage Info/Form

### ISSUE THREAD

**Issue by halfempty** [everythingtype/etc-nyc#23]
![image](https://cloud.githubusercontent.com/assets/775543/4017814/67445af0-2a44-11e4-91ff-e3accb70b6e5.png)

**Comment by gehalber** [comment]
It seems that the confirmation screen isn't doing the black box anymore, which was a nice element we thought.

**Comment by gehalber** [comment]
We also want to add some additional features at the bottom of the homepage. Just a way to get people moving back through the site. This would include some additional links to the Archive and to News. Something like this:

![design-123](https://cloud.githubusercontent.com/assets/6076488/5617280/e91bed4e-94da-11e4-97a6-80a38208ae81.jpg)

**Comment by halfempty** [comment]
@gehalber Black BG is back on form confirmation.

**Comment by halfempty** [comment]
@gehalber Question about homepage "More work" and "News" -- do you want these automatically populated, or hand-picked?

**Comment by gehalber** [comment]
Can we have news feed be most recent and more work be selected?

**Comment by halfempty** [comment]
@gehalber Some progress on the Work/News boxes on the bottom of the homepage...

You'll notice I'm using the same thumbnail-block as elsewhere on the site. The result is slightly different, visually, than the mockup -- the images are bottom-aligned, for instance. The code on these thumbnails is fairly complex (to achieve the layout and animation), so I'd prefer to use them consistently throughout.  But let me know!

**Comment by halfempty** [comment]
@gehalber I'm going to close this issue for now. But if you have any questions about this bit, feel free to re-open.

**Comment by gehalber** [comment]
There are "Info" buttons underneath "see more work" and "news" that shouldn't be there.
Let's make the see more work section 4 images across; same as news.
