### ISSUE TITLE
Slideshow

### ISSUE THREAD

**Issue by halfempty** [everythingtype/etc-nyc#24]

**Comment by gehalber** [comment]
The vertical slideshow is great. We want to remove the white square behind the bespoke cursor.
![design-12](https://cloud.githubusercontent.com/assets/6076488/5617022/f069b80e-94d7-11e4-8b69-3d04f83bd21e.jpg)

**Comment by halfempty** [comment]
Okay, white background removed

**Comment by halfempty** [comment]
@gehalber When you have a chance, it would be helpful to have some more content loaded into the homepage slideshow, so I can see how the coding holds up.

**Comment by gehalber** [comment]
Its up!
