### ISSUE TITLE
Remove Years from Works page

### ISSUE THREAD

**Issue by halfempty** [everythingtype/etc-nyc#26]
Clicking on Work gives you an array of chronologically ordered work, but without the year delineation.

**Comment by gehalber** [comment]
Actually, we're going to remove the labeling at the top of the "Branding" Page. It would just be highlighted in the Nav off to the left. We will also need an entry in the subnav that says "All Projects"
![design-124](https://cloud.githubusercontent.com/assets/6076488/5616889/9ce01864-94d6-11e4-8235-3b3606ff2b4d.jpg)

**Comment by halfempty** [comment]
@gehalber Okay, titles on these pages gone

**Comment by gehalber** [comment]
Can you also have the work flow together so there isn't any demarcation by year. So for example, a project done on 2015 might be on the same line has a project in 2014.

**Comment by halfempty** [comment]
Okay, this is fixed.
