### ISSUE TITLE
Client list on About page

### ISSUE THREAD

**Issue by halfempty** [everythingtype/etc-nyc#28]
In the list of clients on the about page, make these link to projects made for those clients. 
Also this list of clients should be in 2 columns, if possible.

**Comment by gehalber** [comment]
If there are multiple projects from a client, would it be possible to link to a field of projects?

Ala...

![design-1210](https://cloud.githubusercontent.com/assets/6076488/5617321/691114de-94db-11e4-95a7-35ac0c2c9632.jpg)

**Comment by halfempty** [comment]
@gehalber Linking the client names, yes. But it's not automatic-- it's just something you can do in the content, just add links to the page. (And I think it'll be okay to add full-path links, ie. http://revision.etc-nyc...) Does that make sense?

**Comment by gehalber** [comment]
So I can make a grid page called Herman Miller that is kind of like a grid page called branding?

**Comment by halfempty** [comment]
Client pages are like so:

http://revision.etc-nyc.com/clients/fader-magazine/

You can get at them via Dashboard -> Projects -> Clients

**Comment by halfempty** [comment]
@gehalber I'm going to close this, as I believe it's resolved. But if it's not, please reopen!
