### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by gehalber** [everythingtype/etc-nyc#30]
Slightly different nav nomenclature. Featured is actually the homepage. Archive is the work page.

![design-12](https://cloud.githubusercontent.com/assets/6076488/5617109/11c10f88-94d9-11e4-97d0-94e7cda39df1.jpg)

**Comment by gehalber** [comment]
Under Archive: you can select from all of the different genres. See indesign doc for sizing. When you click on say "Branding" it won't be labeled at the top of the page, but rather just remain black on the left side.
![design-124](https://cloud.githubusercontent.com/assets/6076488/5617122/30be8ba4-94d9-11e4-9841-cd44f2b4b650.jpg)

**Comment by halfempty** [comment]
@gehalber Okay, these links are in.

http://revision.etc-nyc.com/typologies/branding/
