### ISSUE TITLE
Project Info

### ISSUE THREAD

**Issue by gehalber** [everythingtype/etc-nyc#31]
We want to be able to access project information at the top of the page and the bottom. We'd like to have an info button beneath the project name at the top of the page. Clicking on Info brings up a lightbox view (ala TW Ryan).

![design-126](https://cloud.githubusercontent.com/assets/6076488/5617152/8baf7a46-94d9-11e4-82be-fe04e51461c5.jpg)

**Comment by gehalber** [comment]
The title and info button are not fixed. When you scroll all the way to the bottom of the page you'll once again access the information and related projects (now as a two column view). Also the text width is now  the same as "News". See indd.
![design-127](https://cloud.githubusercontent.com/assets/6076488/5617204/1448ef40-94da-11e4-8823-d8b961d5a116.jpg)

**Comment by halfempty** [comment]
@gehalber Am I correct in remembering that, at one point, this block was at the bottom, under the slideshows? Are they STILL down there, if you haven't clicked "Info"? Or is this block hidden until you click Info (full TW Ryan styles)?

**Comment by gehalber** [comment]
They're still down there with slightly different width. See example above.

**Comment by halfempty** [comment]
@gehalber I'm still foggy on this point, sorry! So...

The Images and the Info sit in one long column together?
If you click all the way through the images, you end up at Info?
When you click "Info", it slides you down to Info? Or does it collapse Images, so that you're left only with Info?

**Comment by gehalber** [comment]
Sorry not being clear.

It might be redundant, but info exists twice. At top and at bottom. The idea is that its a way to remove having a fixed info button, and ability to read the info once you get to the bottom of the page.

Info exists at top underneath title of project.
If you click, all images hide.
If you scroll to bottom, the info is there along with related projects.

Make sense?

**Comment by halfempty** [comment]
@gehalber AH okay, I think I understand now. Okay, this is in, please take a look...

http://revision.etc-nyc.com/project/perspecta-43-taboo/

**Comment by gehalber** [comment]
Let's bring the title of the piece back in at the bottom.
Also there should be less space between the Info and the top of the first image: about 30px

**Comment by halfempty** [comment]
Project title, like so?

![image](https://cloud.githubusercontent.com/assets/775543/7851471/f4e204f6-04b5-11e5-802c-15b2e61231a7.png)

**Comment by gehalber** [comment]
Should be centered like the top...

**Comment by halfempty** [comment]
Like this:

http://revision.etc-nyc.com/project/spin-magazine-redesign/

?

**Comment by gehalber** [comment]
perfect.
