### ISSUE TITLE
Project Image Size

### ISSUE THREAD

**Issue by gehalber** [everythingtype/etc-nyc#33]
We definitely want to maximize the size of the images on the site as much as possible. So for example on a laptop at 1440px, we'd love to have an image be 960px wide. Like here:

![design-125](https://cloud.githubusercontent.com/assets/6076488/5617422/ba7430d0-94dc-11e4-8360-e450c284369d.jpg)

**Comment by halfempty** [comment]
@gehalber Sure... The nav on the left is 240px wide, so I've set the margin on either side to that amount. And I've set the image column will be as large as it can be, between those margins. And then the image is (at this point) the original uploaded JPG file, which will fill the column up to its native size. Given all that, let me know if it's doing what you'd expect!

**Comment by halfempty** [comment]
@gehalber Also: I want to get the images to vertically center in the available space. But from a CSS point of view, that's easier said than done! So that's something I'm working on...

**Comment by halfempty** [comment]
Okay, I think I've got the image sizes working on Project pages.
