### ISSUE TITLE
Homepage captions

### ISSUE THREAD

**Issue by halfempty** [everythingtype/etc-nyc#35]
@gehalber Question about these, at the base of homepage slides:

![image](https://cloud.githubusercontent.com/assets/775543/6135927/40ba0d56-b132-11e4-949b-beaf3483748b.png)

Are they to be links? If no, that's easy, 'cause that's how they are now.

If yes, how do we want to handle them, from a content-management point of view? Would it be that you would choose from the list of clients already created within WP? Ditto typologies? (Or did you have another thing in mind?)

**Comment by halfempty** [comment]
@gehalber Ps. Now I realize they're not all clients here, some are project/publicaiton titles. Anyhow, let me know what you'd like to do!

**Comment by gehalber** [comment]
Yeah, actually I think these should be what show up in the captions on the grid pages. Not linkable.

**Comment by halfempty** [comment]
>  these should be what show up in the captions on the grid pages

Totally possible. But just for clarity:

- Right now I have it so that we have custom fields for this text. 
- If we change it to be the same text as the grid pages, we'll have a bit less flexibility for how things appear.  

I don't know if having a bit of flexibility is important for the homepage? Or if consistency is its own reward.

Please confirm wether I should switch it to be the same captions as grid, or leave it as custom fields. Thanks!

**Comment by gehalber** [comment]
Let's leave as custom fields.

**Comment by gehalber** [comment]
We just need to include a "Client name" at the top of this. Basically it will look just like the title for a project page (but without the info button).
