### ISSUE TITLE
Homepage revision

### ISSUE THREAD

**Issue by gehalber** [everythingtype/etc-nyc#39]
Hi Marty,
We're changing our mind about the homepage. :) 

Some of our feedback has been that the current homepage doesn't say enough about what we do, nor is it that compelling when compared to the grid of work. That said, its still really important that we explain to folks who we are and we do so we came up with a new bolder approach. 

The idea is that the first screen, a "card" on black slides up when you click either the arrow or the "All Types". The grid of work would be underneath this card.

Also "all types" would change from one font to another in fairly quick succession. These variations of "all types" would be svgs that are all at same exact width so it wouldn't move the lines left and right too much. 

What do you think?

Do you think you could give us an estimate of time on this change?

**Comment by gehalber** [comment]
Here's the pdf: 
https://www.dropbox.com/s/um6t6s05jciwmyj/Design-14.pdf?dl=0

**Comment by halfempty** [comment]
@gehalber Cool! Quick first impression is that this'll be straightforward. Possibly quicker to do this than to finish the bits remaining on the old homepage.

**Comment by gehalber** [comment]
Cool! Let’s do it.

**Comment by gehalber** [comment]
One thing though... we want this opening card to only use the font Nimbus so we can control the combinations better. Once a user moves into the site though, you can turn back on the random font function. Make sense?

We're also working out a bunch of type combinations for the "all types". Should have a bunch of svgs for you tomorrow.d\

**Comment by halfempty** [comment]
@gehalber Did I ever get the "all types" graphics from you?

I've been going back and forth about how to implement them. You know what would be my favorite, actually? To do them as actual fonts, rather than graphics. With each font containing only the seven letters we need. 

It might be slightly more prep work than just exporting SVGs, though I know you're no strangers to creating fonts. Let me know if you'd like to do that, or if we should just do graphics.

**Comment by gehalber** [comment]
we’ve made a bunch of these. in order for them to be the exact same width so the other type on that line doesn’t move back and forth, I think its going to be best to make some svg graphics. We can probably get these over to you on Monday.

**Comment by gehalber** [comment]
Ok, we have lots of types...Looking forward to seeing these animated. there in the folder called: splash-page-01-outlines03-final-outlined.indd

**Comment by gehalber** [comment]
also "Work" should be "work". thanks.

**Comment by halfempty** [comment]
@gehalber I was able to extract many of the fonts, but not all. Here's what I got:

![image](https://cloud.githubusercontent.com/assets/775543/7335063/f850e2d2-eb6b-11e4-9ede-596ca1982e6a.png)

For the ones not ictured, will you check the outline settings? Thanks!

**Comment by halfempty** [comment]
@gehalber Okay, "all types" is flipping now. Please take a look!

Let me know if you'd like any tweaks to the placement of "all types" relative to the surrounding text. 

If you'd like to change the relationships of the different faces within "all types" to eachother, there's an .AI you can tweak. It's in `the dropbox -> all types -> all types work.ai`. You can also add more there, if you want. And once you've tweaked it, let me know and I'll re-export.

**Comment by gehalber** [comment]
cool!
Love it.

could we speed it up a bit?

I dropped the outlined missing types into your drop: splash-page-01-outlines03-final-outlined2.indd

**Comment by halfempty** [comment]
@gehalber okay, the new ones are in, and it's quickened to .8 seconds. take a look?

**Comment by gehalber** [comment]
Cool! This is great.
Let’s try .6 sec.

And can you please change "New York-based” to “NYC-based”?

Thanks!

g

**Comment by gehalber** [comment]
Also, while you’re in there, can you update it so clicking on the homepage as well as Work takes you to the grid, not back to the splash page.

**Comment by halfempty** [comment]
@gehalber 

Okay, .6 seconds is in.

"Not back to splash page" is a bit more of a tricky thing. Really, this is very similar to the "weather" splash page on YBCA. I'm thinking of using the same technique (which uses a cookie), and will harvest some of that code.

**Comment by gehalber** [comment]
Do you think that will work (the cookie)? Hope so, its a little tedious now to always go back to the splash.

Let’s do .5 secs. :)

**Comment by halfempty** [comment]
I figured out a better way than the cookie to leave the splash page. It's the URL switcharoo we observed over at WAX. It works! Take a look:

http://revision.etc-nyc.com/

Clicking the down arrow switches the URL to /everything. When you access this URL directly, for instance by clicking "Work" in the nav, there's no intro shade. But if you go to the site root, such as by clicking "Everything Type Company", you do get the intro shade.

**Comment by gehalber** [comment]
This is great!
That said, I think we might want the Everything Type Company button to actually take you to “work" as well.

**Comment by halfempty** [comment]
"ETC" link updated.
Dito the down arrow icon.

I think this ticket is done? (Responsive not withstanding)

**Comment by gehalber** [comment]
Sorry, scratch that, almost there. We were going to do a circle around the arrow. And I think the arrow might be a little bit too bold at the moment. It should be the same weight stroke at the sans serif type:

![screen shot 2015-05-27 at 10 16 16 pm](https://cloud.githubusercontent.com/assets/6076488/7851455/194c7530-04be-11e5-8a5e-99ecf6aa4ac1.png)

**Comment by halfempty** [comment]
@gehalber I think maybe your cache needs to be refreshed? (To get the latest version of the icons webfont including the circle graphic)

**Comment by gehalber** [comment]
Bingo! Can you just hover to white, then we can close. 
:)

**Comment by KyleETC** [comment]
Looks great. But, I am unable to see the interchanging/rotating type in Safari. 
Can you take a look at that?

**Comment by halfempty** [comment]
@KyleETC Okay, yeah, I see it. And it's broken in a different way on FF. Thanks!

**Comment by halfempty** [comment]
Okay, fixed!

**Comment by KyleETC** [comment]
Great.

Everything Type Company
117 Dobbin Street, #203
Brooklyn, NY 11211

347-587-9315
www.everything-type-company.com

Kyle Blue
Partner & Creative Director
