### ISSUE TITLE
Forms?

### ISSUE THREAD

**Issue by halfempty** [everythingtype/etc-nyc#40]
@gehalber With the homepage revision we're dropping the contact form. Can I remove the code for forms? Or will a form resurface elsewhere?

**Comment by gehalber** [comment]
I was thinking about that. At the moment, I don’t know if need it, but it could potentially go on the contact page. Will you have that code stored somewhere until a later date?

**Comment by halfempty** [comment]
@gehalber No need to decide right this moment. If we don't end up using a form, this ticket can be a reminder to me to clear out the code.
