### ISSUE TITLE
Box Alignment

### ISSUE THREAD

**Issue by halfempty** [everythingtype/etc-nyc#41]
@gehalber @KyleETC 

Hey guys, I notice that the alignment within the "Related Projects" box is off:

![image](https://cloud.githubusercontent.com/assets/775543/7217306/0687c7be-e5e8-11e4-8d3e-980f2a16f56c.png)

So I'm going to take a look at it. Also, I wanted to confirm that bottom alignment, as seen here:

![image](https://cloud.githubusercontent.com/assets/775543/7217308/2d23f550-e5e8-11e4-89f8-b1f3255a8dd6.png)

is the correct thing?

**Comment by gehalber** [comment]
Great. yes, the bottom alignment is correct.

**Comment by halfempty** [comment]
Fixed
