### ISSUE TITLE
Everything v. Selected Projects

### ISSUE THREAD

**Issue by gehalber** [everythingtype/etc-nyc#43]
Ok. Now that we're populating our site with more work, we realize it might be nice to have the homepage grid be selected projects only. Then there is the option to select "Everything". Would this be easy to integrate?

**Comment by halfempty** [comment]
@gehalber Perhaps "Selected"/"Featured" be a taxonomy, like Publications? That'd be really simple, requiring little new coding.

**Comment by gehalber** [comment]
That's fine. Maybe we would just double up the categories so for example with SPIN it would be featured and a publication. 

Is there a way to preference one category over the other in the captioning underneath the images in the grid?

**Comment by halfempty** [comment]
@gehalber One question before I go to implement this...

Would you want "Everything" to be pretty much how it is? OR, should "Everything" be the Index-style screen?

![screen shot 2015-01-20 at 12 51 41 am](https://cloud.githubusercontent.com/assets/6076488/5812745/eee1ca5e-a03e-11e4-874c-d53a168a611d.png)
