### ISSUE TITLE
Change the Captions information

### ISSUE THREAD

**Issue by halfempty** [everythingtype/etc-nyc#48]
Change the Captions information under projects to:
First Line (Black): Project Title
Second Line (Gray): Project Types (e.g. Branding, Publications, Interactive Design)  
Third Line (Gray): Fonts used (e.g. Futura, Plantin)

**Comment by halfempty** [comment]
@gehalber Making sure I'm clear. For instance, this:

![image](https://cloud.githubusercontent.com/assets/775543/11221421/a5493ab0-8d2a-11e5-8ba6-5997bff51602.png)

becomes:

Third & Mission
Branding, Publication, Website
Interstate, Kievit

**Comment by gehalber** [comment]
Yes, but let’s add Fonts before the line:

Third & Mission
Branding, Publication, Website
Fonts: Interstate, Kievit

**Comment by halfempty** [comment]
Done
