### ISSUE TITLE
Image load times

### ISSUE THREAD

**Issue by halfempty** [everythingtype/etc-nyc#51]
I feel like they're a thing, just like on JSA (it's the same code in there)

**Comment by gehalber** [comment]
Yeah, we’ve been making them 2400px and saving for web. Our internet is a bit faster these days so we’re not seeing it as much.

What should we do?

**Comment by halfempty** [comment]
Oh, it's a code thing. No re-uploading will be required

**Comment by halfempty** [comment]
Made a tweak that I hope helps with this
